// UI strings for the admin panel itself, in all three languages.
// The admin's language dropdown switches both the content being edited AND
// this interface text.

import type { Lang } from './detectLanguage';

export type AdminKey =
  | 'adminTitle' | 'adminSubtitle'
  | 'tabContent' | 'tabProducts' | 'tabRequests'
  | 'viewSite' | 'logout' | 'save' | 'saved'
  | 'language'
  | 'howTitle' | 'howBody'
  | 'searchPlaceholder' | 'hidePreview' | 'showPreview' | 'export' | 'import' | 'reset'
  | 'applying' | 'livePreview' | 'contentNote'
  | 'requestsTitle' | 'requestsSubtitle' | 'requestsNote'
  | 'fAll' | 'fMessages' | 'fBookings' | 'csv' | 'clear'
  | 'noRequests' | 'noRequestsBody' | 'markRead' | 'markUnread' | 'delete'
  | 'productsTitle' | 'productsEditingPre' | 'productsEditingPost'
  | 'addProduct' | 'addFirstProduct' | 'noProducts'
  | 'replace' | 'upload' | 'title' | 'category' | 'description' | 'specs' | 'addSpec' | 'deleteProduct'
  | 'addItem' | 'categoryPlaceholder' | 'productsNote'
  | 'selectCategory' | 'addNewCategory' | 'newCategoryPlaceholder' | 'categoryHelp'
  | 'loginTitle' | 'loginSubtitle' | 'username' | 'password' | 'wrongCreds' | 'checking' | 'signIn' | 'backToSite'
  | 'confirmResetContent' | 'confirmResetProducts' | 'confirmDeleteProduct' | 'confirmClearRequests'
  | 'imported' | 'importError' | 'imageTooBig'
  | 'tabGallery' | 'galleryTitle' | 'gallerySubtitle' | 'addImage' | 'addFirstImage' | 'noImages'
  | 'galleryNote' | 'confirmDeleteImage' | 'confirmResetGallery' | 'photoCategory'
  | 'showInGallery' | 'hideFromGallery' | 'hiddenLabel'
  | 'pageImages' | 'mainBanner' | 'aboutImage' | 'fromGallery' | 'remove' | 'noGalleryYet'
  | 'brandName' | 'brandNameHint'
  | 'socialLinks' | 'socialHint' | 'addSocial' | 'socialUrlPlaceholder'
  | 'adminLogin' | 'adminLoginHint' | 'newUsername' | 'newPassword' | 'updateLogin' | 'loginUpdated' | 'loginInvalid'
  | 'loadingSite' | 'loadFailed' | 'retry' | 'notPublishedYet' | 'publishing' | 'uploadingImages' | 'publishFailed' | 'conflictOverwrite' | 'conflictInfo' | 'sessionExpired' | 'tooManyAttempts' | 'notConfigured' | 'serverUnreachable' | 'requestsLoadFailed' | 'refresh' | 'accountFailed'
  | 'navDashboard' | 'navPages' | 'navTheme' | 'navSettings' | 'interfaceLanguage' | 'editingLanguage'
  | 'publish' | 'statusPublished' | 'statusUnsaved' | 'statusNever' | 'discard' | 'confirmDiscard'
  | 'lastPublished' | 'shortcutHint' | 'welcome' | 'dashboardIntro' | 'cardSiteStatus' | 'cardTheme'
  | 'cardRequests' | 'cardContent' | 'productsCount' | 'photosCount' | 'languagesCount' | 'quickActions'
  | 'actEditHome' | 'actChangeTheme' | 'actViewRequests' | 'latestRequests' | 'viewAll' | 'unreadCount'
  | 'pagesSubtitle' | 'pageHeader' | 'pageHome' | 'pageAbout' | 'pageProducts' | 'pageGallery'
  | 'pageContact' | 'pageBooking' | 'pageFooter' | 'pageSeo' | 'pageOther' | 'compareLangs'
  | 'visibleSections' | 'sec_headerBook' | 'sec_heroStats' | 'sec_homeFeatures' | 'sec_homeManufacturing' | 'sec_homeCta'
  | 'sec_footerAdminLink' | 'logo' | 'homeImage' | 'pageImagesHint' | 'bookingTimes' | 'bookingTimesHint'
  | 'addTime' | 'bookingDays' | 'seoHint' | 'noFieldsMatch' | 'textsSection' | 'imagesSection'
  | 'deviceDesktop' | 'deviceTablet' | 'deviceMobile' | 'previewDraftNote' | 'openPreview' | 'close'
  | 'themeSubtitle' | 'currentBadge' | 'defaultBadge' | 'darkBadge' | 'customize' | 'customizeHint'
  | 'primaryColor' | 'accentColor' | 'headingFont' | 'bodyFont' | 'corners' | 'cornersTheme'
  | 'cornersSharp' | 'cornersSoft' | 'cornersRound' | 'resetCustom' | 'fontsNote' | 'settingsSubtitle'
  | 'brandSection' | 'backupTitle' | 'backupHint' | 'downloadBackup' | 'restoreBackup' | 'restored'
  | 'resetAllTitle' | 'resetAllHint' | 'confirmResetAll' | 'resetPage' | 'confirmResetPage' | 'menu'
  | 'remoteNewer' | 'loadLatest' | 'newBadge' | 'missingTranslation' | 'invalidTime' | 'confirmRestore' | 'notBackup' | 'page404';

type Dict = Record<AdminKey, string>;

const en: Dict = {
  adminTitle: 'Döwletli Admin',
  adminSubtitle: 'Manage your website',
  tabContent: 'Content',
  tabProducts: 'Products',
  tabRequests: 'Requests',
  viewSite: 'View site',
  logout: 'Logout',
  save: 'Save',
  saved: 'Published',
  language: 'Language',
  howTitle: 'How it works:',
  howBody: 'pick a language and edit any text, then press Publish. Nothing changes on the site until you publish. Manage products and photos in the Products and Gallery tabs.',
  searchPlaceholder: 'Search text…',
  hidePreview: 'Hide preview',
  showPreview: 'Show preview',
  export: 'Export',
  import: 'Import',
  reset: 'Reset',
  applying: 'You have unpublished changes — press Publish to make them live.',
  livePreview: 'Live preview',
  contentNote: 'Press Publish — changes go live for every visitor right away. Use Export to keep a backup of your texts.',
  requestsTitle: 'Requests',
  requestsSubtitle: 'Contact messages and consultation bookings from your website.',
  requestsNote: 'Messages and bookings from every visitor are stored on the server and appear here on any device.',
  fAll: 'All',
  fMessages: 'Messages',
  fBookings: 'Bookings',
  csv: 'CSV',
  clear: 'Clear',
  noRequests: 'No requests yet',
  noRequestsBody: 'Contact messages and consultation bookings from the website will appear here.',
  markRead: 'Mark read',
  markUnread: 'Mark unread',
  delete: 'Delete',
  productsTitle: 'Products',
  productsEditingPre: 'Add, remove and edit products and their photos. You are editing the ',
  productsEditingPost: ' texts.',
  addProduct: 'Add product',
  addFirstProduct: 'Add your first product',
  noProducts: 'No products yet',
  replace: 'Replace',
  upload: 'Upload',
  title: 'Title',
  category: 'Category',
  description: 'Description',
  specs: 'Specs',
  addSpec: 'Add spec',
  deleteProduct: 'Delete product',
  addItem: 'Add item',
  categoryPlaceholder: 'e.g. aerial, underground, ftth…',
  selectCategory: 'Select category…',
  addNewCategory: 'Add new category…',
  newCategoryPlaceholder: 'New category name',
  categoryHelp: 'Pick a category or add your own. It shows on the product card.',
  productsNote: 'Press Publish. Uploaded images are stored on the server and resized automatically.',
  loginTitle: 'Admin Panel',
  loginSubtitle: 'Döwletli content editor',
  username: 'Username',
  password: 'Password',
  wrongCreds: 'Wrong username or password.',
  checking: 'Checking…',
  signIn: 'Sign in',
  backToSite: '← Back to website',
  confirmResetContent: 'Reset ALL texts back to the original defaults? This cannot be undone.',
  confirmResetProducts: 'Reset products to the original 5?',
  confirmDeleteProduct: 'Delete this product? This cannot be undone.',
  confirmClearRequests: 'Delete ALL requests?',
  imported: 'Imported. Press Publish.',
  importError: 'Could not read that file. Make sure it is a valid export.',
  imageTooBig: 'This image is too large. Please use a file under 20 MB.',
  tabGallery: 'Gallery',
  galleryTitle: 'Gallery',
  gallerySubtitle: 'Add or remove the photos shown on the Gallery page, and pick page images.',
  addImage: 'Add photo',
  addFirstImage: 'Add your first photo',
  noImages: 'No photos yet',
  galleryNote: 'Press Publish. Photos are stored on the server and resized automatically. Use the eye icon to hide a photo from the Gallery page without deleting it.',
  confirmDeleteImage: 'Remove this photo?',
  confirmResetGallery: 'Reset gallery to the original photos?',
  photoCategory: 'Category',
  showInGallery: 'Show in gallery',
  hideFromGallery: 'Hide from gallery',
  hiddenLabel: 'Hidden',
  pageImages: 'Page images',
  mainBanner: 'Home — main banner',
  aboutImage: 'About — photo',
  fromGallery: 'From gallery',
  remove: 'Remove',
  noGalleryYet: 'No gallery photos yet — add some below.',
  brandName: 'Brand name (header & footer)',
  brandNameHint: 'Shown at the top of every page. Same in all languages.',
  socialLinks: 'Social links (Contact & footer)',
  socialHint: 'Pick a platform and paste the link. Empty ones are hidden on the site.',
  addSocial: 'Add social link',
  socialUrlPlaceholder: 'https://… or wa.me/…',
  adminLogin: 'Admin login',
  adminLoginHint: 'Change the username and password used to sign in to this panel.',
  newUsername: 'Username',
  newPassword: 'New password (min 8 characters)',
  updateLogin: 'Update login',
  loginUpdated: 'Login updated. Use the new username and password next time.',
  loginInvalid: 'Enter a username and a password of at least 8 characters.',
  loadingSite: 'Loading the published site…',
  loadFailed: 'Could not load the published content from the server. Check your connection and try again — saving is disabled until it loads.',
  retry: 'Retry',
  notPublishedYet: 'Nothing has been published to the server yet — visitors currently see the default texts. Review the content and press Publish to make it live for everyone.',
  publishing: 'Publishing…',
  uploadingImages: 'Uploading images…',
  publishFailed: 'Publishing failed — your changes are NOT live yet. Please try again.',
  conflictOverwrite: 'The site was changed from another device or tab since you opened the panel. Overwrite it with your version?',
  conflictInfo: 'Not saved. Reload the panel to get the latest version, then re-apply your changes.',
  sessionExpired: 'Your session has expired. Please sign in again.',
  tooManyAttempts: 'Too many failed attempts. Please wait 15 minutes and try again.',
  notConfigured: 'Admin login is not configured on the server yet (the ADMIN_PASSWORD secret is missing in Cloudflare).',
  serverUnreachable: 'Cannot reach the server. Check your connection and try again.',
  requestsLoadFailed: 'Could not load requests from the server.',
  refresh: 'Refresh',
  accountFailed: 'Could not update the login. Please try again.',
  navDashboard: 'Dashboard',
  navPages: 'Pages & texts',
  navTheme: 'Theme & design',
  navSettings: 'Settings',
  interfaceLanguage: 'Panel language',
  editingLanguage: 'Editing language',
  publish: 'Publish',
  statusPublished: 'All changes are live',
  statusUnsaved: 'Unpublished changes',
  statusNever: 'Not published yet',
  discard: 'Discard changes',
  confirmDiscard: 'Discard all unpublished changes?',
  lastPublished: 'Last published',
  shortcutHint: 'Tip: Ctrl / ⌘ + S publishes',
  welcome: 'Welcome back',
  dashboardIntro: 'Everything on the website is managed here — texts, images, products, theme and requests.',
  cardSiteStatus: 'Site status',
  cardTheme: 'Current theme',
  cardRequests: 'New requests',
  cardContent: 'Content',
  productsCount: 'products',
  photosCount: 'gallery photos',
  languagesCount: 'languages',
  quickActions: 'Quick actions',
  actEditHome: 'Edit home page',
  actChangeTheme: 'Change theme',
  actViewRequests: 'View requests',
  latestRequests: 'Latest requests',
  viewAll: 'View all',
  unreadCount: 'unread',
  pagesSubtitle: 'Pick a page, edit its texts and images, and watch the preview update live.',
  pageHeader: 'Header & menu',
  pageHome: 'Home page',
  pageAbout: 'About us',
  pageProducts: 'Products page',
  pageGallery: 'Gallery page',
  pageContact: 'Contact',
  pageBooking: 'Booking',
  pageFooter: 'Footer',
  pageSeo: 'SEO & browser tab',
  pageOther: 'Other texts',
  compareLangs: 'Show all 3 languages',
  visibleSections: 'Show / hide sections',
  sec_headerBook: '“Book” button in the header',
  sec_heroStats: 'Stats under the main image',
  sec_homeFeatures: 'Feature cards',
  sec_homeManufacturing: 'Manufacturing block',
  sec_homeCta: 'Call-to-action banner',
  sec_footerAdminLink: '“Admin” link in the footer',
  logo: 'Logo (also the browser-tab icon)',
  homeImage: 'Home — manufacturing photo',
  pageImagesHint: 'Pick from the gallery or upload a new image.',
  bookingTimes: 'Available time slots',
  bookingTimesHint: 'Visitors can choose one of these times.',
  addTime: 'Add time',
  bookingDays: 'Days shown ahead',
  seoHint: 'Shown in the browser tab and in Google search results.',
  noFieldsMatch: 'No fields match your search.',
  textsSection: 'Texts',
  imagesSection: 'Images',
  deviceDesktop: 'Desktop',
  deviceTablet: 'Tablet',
  deviceMobile: 'Mobile',
  previewDraftNote: 'Shows your unpublished changes',
  openPreview: 'Preview',
  close: 'Close',
  themeSubtitle: 'Choose a theme for the whole website. It shows in the preview right away and goes live when you publish.',
  currentBadge: 'Selected',
  defaultBadge: 'Original',
  darkBadge: 'Dark',
  customize: 'Fine-tune',
  customizeHint: 'Optional: adjust the selected theme. Leave empty to use the theme’s own values.',
  primaryColor: 'Main color',
  accentColor: 'Accent color',
  headingFont: 'Heading font',
  bodyFont: 'Text font',
  corners: 'Corners',
  cornersTheme: 'As in theme',
  cornersSharp: 'Sharp',
  cornersSoft: 'Soft',
  cornersRound: 'Round',
  resetCustom: 'Reset fine-tuning',
  fontsNote: 'All fonts support Latin, Türkmen and Cyrillic letters.',
  settingsSubtitle: 'Brand, social links, admin login and backups.',
  brandSection: 'Brand',
  backupTitle: 'Backup & restore',
  backupHint: 'Download everything (texts, products, gallery, theme, settings) as one file, or load it back.',
  downloadBackup: 'Download backup',
  restoreBackup: 'Load from file',
  restored: 'Backup loaded. Check the preview, then press Publish.',
  resetAllTitle: 'Reset everything',
  resetAllHint: 'Restore all texts, products, gallery, theme and settings to the original website. Nothing changes until you publish.',
  confirmResetAll: 'Reset everything to the original website? Nothing changes until you publish.',
  resetPage: 'Reset this page',
  confirmResetPage: 'Reset this page’s texts (all languages) to the original?',
  menu: 'Menu',
  remoteNewer: 'The website was updated from another device or tab. Load the latest version so you don’t overwrite it.',
  loadLatest: 'Load latest',
  newBadge: 'new',
  missingTranslation: 'Missing translation — English is shown instead',
  invalidTime: 'Use the format HH:MM, e.g. 09:30',
  confirmRestore: 'Load this backup? It replaces your current unpublished draft (nothing goes live until you publish).',
  notBackup: 'This file is not a Döwletli backup.',
  page404: 'Not-found page (404)',
};

const ru: Dict = {
  adminTitle: 'Döwletli Admin',
  adminSubtitle: 'Управление сайтом',
  tabContent: 'Тексты',
  tabProducts: 'Продукция',
  tabRequests: 'Заявки',
  viewSite: 'Открыть сайт',
  logout: 'Выйти',
  save: 'Сохранить',
  saved: 'Опубликовано',
  language: 'Язык',
  howTitle: 'Как это работает:',
  howBody: 'выберите язык и редактируйте текст, затем нажмите «Опубликовать». До сохранения на сайте ничего не меняется. Продукцию и фото меняйте во вкладках «Продукция» и «Галерея».',
  searchPlaceholder: 'Поиск текста…',
  hidePreview: 'Скрыть предпросмотр',
  showPreview: 'Показать предпросмотр',
  export: 'Экспорт',
  import: 'Импорт',
  reset: 'Сброс',
  applying: 'Есть несохранённые изменения — нажмите «Опубликовать».',
  livePreview: 'Предпросмотр',
  contentNote: 'Нажмите «Опубликовать» — изменения сразу видны всем посетителям. Используйте «Экспорт» для резервной копии текстов.',
  requestsTitle: 'Заявки',
  requestsSubtitle: 'Сообщения и записи на консультацию с вашего сайта.',
  requestsNote: 'Сообщения и заявки всех посетителей хранятся на сервере и видны здесь с любого устройства.',
  fAll: 'Все',
  fMessages: 'Сообщения',
  fBookings: 'Записи',
  csv: 'CSV',
  clear: 'Очистить',
  noRequests: 'Пока нет заявок',
  noRequestsBody: 'Сообщения и записи на консультацию с сайта появятся здесь.',
  markRead: 'Прочитано',
  markUnread: 'Непрочитано',
  delete: 'Удалить',
  productsTitle: 'Продукция',
  productsEditingPre: 'Добавляйте, удаляйте и редактируйте продукты и их фото. Вы редактируете тексты на языке ',
  productsEditingPost: '.',
  addProduct: 'Добавить продукт',
  addFirstProduct: 'Добавьте первый продукт',
  noProducts: 'Пока нет продуктов',
  replace: 'Заменить',
  upload: 'Загрузить',
  title: 'Название',
  category: 'Категория',
  description: 'Описание',
  specs: 'Характеристики',
  addSpec: 'Добавить характеристику',
  deleteProduct: 'Удалить продукт',
  addItem: 'Добавить',
  categoryPlaceholder: 'напр. aerial, underground, ftth…',
  selectCategory: 'Выберите категорию…',
  addNewCategory: 'Добавить новую категорию…',
  newCategoryPlaceholder: 'Название новой категории',
  categoryHelp: 'Выберите категорию или добавьте свою. Она показывается на карточке продукта.',
  productsNote: 'Нажмите «Опубликовать», чтобы изменения появились на сайте. Загруженные фото хранятся на сервере и автоматически уменьшаются.',
  loginTitle: 'Панель администратора',
  loginSubtitle: 'Редактор сайта Döwletli',
  username: 'Имя пользователя',
  password: 'Пароль',
  wrongCreds: 'Неверное имя пользователя или пароль.',
  checking: 'Проверка…',
  signIn: 'Войти',
  backToSite: '← Назад на сайт',
  confirmResetContent: 'Сбросить ВСЕ тексты к исходным? Это нельзя отменить.',
  confirmResetProducts: 'Вернуть исходные 5 продуктов?',
  confirmDeleteProduct: 'Удалить этот продукт? Это нельзя отменить.',
  confirmClearRequests: 'Удалить ВСЕ заявки?',
  imported: 'Импортировано. Нажмите «Опубликовать».',
  importError: 'Не удалось прочитать файл. Убедитесь, что это корректный экспорт.',
  imageTooBig: 'Изображение слишком большое. Используйте файл меньше 20 МБ.',
  tabGallery: 'Галерея',
  galleryTitle: 'Галерея',
  gallerySubtitle: 'Добавляйте и удаляйте фото галереи и выбирайте изображения страниц.',
  addImage: 'Добавить фото',
  addFirstImage: 'Добавьте первое фото',
  noImages: 'Пока нет фото',
  galleryNote: 'Нажмите «Опубликовать», чтобы изменения появились на сайте. Фото хранятся на сервере и автоматически уменьшаются. Нажмите на значок глаза, чтобы скрыть фото со страницы галереи, не удаляя его.',
  confirmDeleteImage: 'Удалить это фото?',
  confirmResetGallery: 'Вернуть исходные фото галереи?',
  photoCategory: 'Категория',
  showInGallery: 'Показывать в галерее',
  hideFromGallery: 'Скрыть из галереи',
  hiddenLabel: 'Скрыто',
  pageImages: 'Изображения страниц',
  mainBanner: 'Главная — баннер',
  aboutImage: 'О нас — фото',
  fromGallery: 'Из галереи',
  remove: 'Удалить',
  noGalleryYet: 'В галерее пока нет фото — добавьте ниже.',
  brandName: 'Название бренда (шапка и подвал)',
  brandNameHint: 'Показывается вверху каждой страницы. Одинаково на всех языках.',
  socialLinks: 'Соцсети (Контакты и подвал)',
  socialHint: 'Выберите платформу и вставьте ссылку. Пустые не показываются на сайте.',
  addSocial: 'Добавить соцсеть',
  socialUrlPlaceholder: 'https://… или wa.me/…',
  adminLogin: 'Вход администратора',
  adminLoginHint: 'Измените имя пользователя и пароль для входа в эту панель.',
  newUsername: 'Имя пользователя',
  newPassword: 'Новый пароль (мин. 8 символов)',
  updateLogin: 'Обновить вход',
  loginUpdated: 'Данные обновлены. Используйте новый логин и пароль при следующем входе.',
  loginInvalid: 'Введите имя пользователя и пароль не менее 8 символов.',
  loadingSite: 'Загрузка опубликованного сайта…',
  loadFailed: 'Не удалось загрузить опубликованный контент с сервера. Проверьте соединение и попробуйте снова — сохранение недоступно до загрузки.',
  retry: 'Повторить',
  notPublishedYet: 'На сервер ещё ничего не опубликовано — посетители сейчас видят тексты по умолчанию. Проверьте контент и нажмите «Опубликовать», чтобы сайт обновился для всех.',
  publishing: 'Публикация…',
  uploadingImages: 'Загрузка изображений…',
  publishFailed: 'Не удалось опубликовать — изменения ещё НЕ на сайте. Попробуйте снова.',
  conflictOverwrite: 'С момента открытия панели сайт был изменён с другого устройства или вкладки. Перезаписать его вашей версией?',
  conflictInfo: 'Не сохранено. Обновите панель, чтобы получить последнюю версию, и внесите изменения заново.',
  sessionExpired: 'Сессия истекла. Войдите снова.',
  tooManyAttempts: 'Слишком много неудачных попыток. Подождите 15 минут и попробуйте снова.',
  notConfigured: 'Вход администратора ещё не настроен на сервере (в Cloudflare нет секрета ADMIN_PASSWORD).',
  serverUnreachable: 'Нет связи с сервером. Проверьте соединение и попробуйте снова.',
  requestsLoadFailed: 'Не удалось загрузить заявки с сервера.',
  refresh: 'Обновить',
  accountFailed: 'Не удалось обновить вход. Попробуйте снова.',
  navDashboard: 'Обзор',
  navPages: 'Страницы и тексты',
  navTheme: 'Тема и дизайн',
  navSettings: 'Настройки',
  interfaceLanguage: 'Язык панели',
  editingLanguage: 'Язык редактирования',
  publish: 'Опубликовать',
  statusPublished: 'Все изменения опубликованы',
  statusUnsaved: 'Есть неопубликованные изменения',
  statusNever: 'Ещё не опубликовано',
  discard: 'Отменить изменения',
  confirmDiscard: 'Отменить все неопубликованные изменения?',
  lastPublished: 'Последняя публикация',
  shortcutHint: 'Подсказка: Ctrl / ⌘ + S — опубликовать',
  welcome: 'С возвращением',
  dashboardIntro: 'Здесь управляется всё на сайте — тексты, изображения, продукция, тема и заявки.',
  cardSiteStatus: 'Статус сайта',
  cardTheme: 'Текущая тема',
  cardRequests: 'Новые заявки',
  cardContent: 'Контент',
  productsCount: 'продуктов',
  photosCount: 'фото в галерее',
  languagesCount: 'языка',
  quickActions: 'Быстрые действия',
  actEditHome: 'Редактировать главную',
  actChangeTheme: 'Сменить тему',
  actViewRequests: 'Открыть заявки',
  latestRequests: 'Последние заявки',
  viewAll: 'Все',
  unreadCount: 'непрочитанных',
  pagesSubtitle: 'Выберите страницу, меняйте тексты и изображения — предпросмотр обновляется сразу.',
  pageHeader: 'Шапка и меню',
  pageHome: 'Главная',
  pageAbout: 'О нас',
  pageProducts: 'Страница продукции',
  pageGallery: 'Страница галереи',
  pageContact: 'Контакты',
  pageBooking: 'Запись',
  pageFooter: 'Подвал',
  pageSeo: 'SEO и вкладка браузера',
  pageOther: 'Прочие тексты',
  compareLangs: 'Показать все 3 языка',
  visibleSections: 'Показать / скрыть разделы',
  sec_headerBook: 'Кнопка «Записаться» в шапке',
  sec_heroStats: 'Цифры под главным изображением',
  sec_homeFeatures: 'Карточки преимуществ',
  sec_homeManufacturing: 'Блок о производстве',
  sec_homeCta: 'Баннер с призывом',
  sec_footerAdminLink: 'Ссылка «Админ» в подвале',
  logo: 'Логотип (и значок вкладки)',
  homeImage: 'Главная — фото производства',
  pageImagesHint: 'Выберите из галереи или загрузите новое изображение.',
  bookingTimes: 'Доступное время',
  bookingTimesHint: 'Посетители выбирают одно из этих времён.',
  addTime: 'Добавить время',
  bookingDays: 'Сколько дней показывать',
  seoHint: 'Отображается во вкладке браузера и в результатах Google.',
  noFieldsMatch: 'Нет полей по вашему запросу.',
  textsSection: 'Тексты',
  imagesSection: 'Изображения',
  deviceDesktop: 'Компьютер',
  deviceTablet: 'Планшет',
  deviceMobile: 'Телефон',
  previewDraftNote: 'Показывает неопубликованные изменения',
  openPreview: 'Предпросмотр',
  close: 'Закрыть',
  themeSubtitle: 'Выберите тему для всего сайта. Она сразу видна в предпросмотре и публикуется кнопкой «Опубликовать».',
  currentBadge: 'Выбрана',
  defaultBadge: 'Оригинал',
  darkBadge: 'Тёмная',
  customize: 'Тонкая настройка',
  customizeHint: 'Необязательно: подстройте выбранную тему. Оставьте пустым — будут значения темы.',
  primaryColor: 'Основной цвет',
  accentColor: 'Акцентный цвет',
  headingFont: 'Шрифт заголовков',
  bodyFont: 'Шрифт текста',
  corners: 'Углы',
  cornersTheme: 'Как в теме',
  cornersSharp: 'Острые',
  cornersSoft: 'Мягкие',
  cornersRound: 'Круглые',
  resetCustom: 'Сбросить настройку',
  fontsNote: 'Все шрифты поддерживают латиницу, туркменские буквы и кириллицу.',
  settingsSubtitle: 'Бренд, соцсети, вход администратора и резервные копии.',
  brandSection: 'Бренд',
  backupTitle: 'Резервная копия',
  backupHint: 'Скачайте всё (тексты, продукцию, галерею, тему, настройки) одним файлом или загрузите обратно.',
  downloadBackup: 'Скачать копию',
  restoreBackup: 'Загрузить из файла',
  restored: 'Копия загружена. Проверьте предпросмотр и нажмите «Опубликовать».',
  resetAllTitle: 'Сбросить всё',
  resetAllHint: 'Вернуть все тексты, продукцию, галерею, тему и настройки к исходному сайту. Ничего не изменится до публикации.',
  confirmResetAll: 'Сбросить всё к исходному сайту? Ничего не изменится до публикации.',
  resetPage: 'Сбросить страницу',
  confirmResetPage: 'Сбросить тексты этой страницы (все языки) к исходным?',
  menu: 'Меню',
  remoteNewer: 'Сайт был обновлён с другого устройства или вкладки. Загрузите последнюю версию, чтобы не перезаписать её.',
  loadLatest: 'Загрузить последнюю',
  newBadge: 'новая',
  missingTranslation: 'Нет перевода — будет показан английский',
  invalidTime: 'Используйте формат ЧЧ:ММ, например 09:30',
  confirmRestore: 'Загрузить эту копию? Она заменит текущий черновик (на сайт ничего не попадёт до публикации).',
  notBackup: 'Этот файл не является резервной копией Döwletli.',
  page404: 'Страница «не найдено» (404)',
};

const tkm: Dict = {
  adminTitle: 'Döwletli Admin',
  adminSubtitle: 'Web sahypaňyzy dolandyryň',
  tabContent: 'Tekstler',
  tabProducts: 'Önümler',
  tabRequests: 'Haýyşlar',
  viewSite: 'Sahypany aç',
  logout: 'Çykmak',
  save: 'Ýatda saklamak',
  saved: 'Çap edildi',
  language: 'Dil',
  howTitle: 'Nähili işleýär:',
  howBody: 'dili saýlaň we teksti redaktirläň, soňra «Çap et» basyň. Saklaýançaňyz sahypada hiç zat üýtgemeýär. Önümleri we suratlary «Önümler» we «Galereýa» bölümlerinde dolandyryň.',
  searchPlaceholder: 'Tekst gözle…',
  hidePreview: 'Önizlemäni gizle',
  showPreview: 'Önizlemäni görkez',
  export: 'Eksport',
  import: 'Import',
  reset: 'Dikeltmek',
  applying: 'Saklanmadyk üýtgeşmeler bar — «Çap et» basyň.',
  livePreview: 'Janly önizleme',
  contentNote: '«Çap et» basyň — üýtgeşmeler derrew ähli myhmanlara görünýär. Tekstleriň ätiýaçlyk nusgasy üçin «Eksport» ulanyň.',
  requestsTitle: 'Haýyşlar',
  requestsSubtitle: 'Sahypaňyzdan gelen habarlar we maslahat ýazgylary.',
  requestsNote: 'Ähli myhmanlaryň habarlary we ýazylyşlary serwerde saklanýar we islendik enjamda şu ýerde görünýär.',
  fAll: 'Hemmesi',
  fMessages: 'Habarlar',
  fBookings: 'Ýazgylar',
  csv: 'CSV',
  clear: 'Arassala',
  noRequests: 'Heniz haýyş ýok',
  noRequestsBody: 'Sahypadan gelen habarlar we maslahat ýazgylary şu ýerde görüner.',
  markRead: 'Okaldy diýip belle',
  markUnread: 'Okalmady diýip belle',
  delete: 'Poz',
  productsTitle: 'Önümler',
  productsEditingPre: 'Önümleri we suratlaryny goşuň, pozuň we redaktirläň. Siz ',
  productsEditingPost: ' dilindäki tekstleri redaktirleýärsiňiz.',
  addProduct: 'Önüm goş',
  addFirstProduct: 'Ilkinji önümiňizi goşuň',
  noProducts: 'Heniz önüm ýok',
  replace: 'Çalyş',
  upload: 'Ýükle',
  title: 'Ady',
  category: 'Kategoriýa',
  description: 'Düşündiriş',
  specs: 'Aýratynlyklar',
  addSpec: 'Aýratynlyk goş',
  deleteProduct: 'Önümi poz',
  addItem: 'Goş',
  categoryPlaceholder: 'mysal: aerial, underground, ftth…',
  selectCategory: 'Kategoriýa saýlaň…',
  addNewCategory: 'Täze kategoriýa goş…',
  newCategoryPlaceholder: 'Täze kategoriýanyň ady',
  categoryHelp: 'Kategoriýa saýlaň ýa-da öz kategoriýaňyzy goşuň. Önüm kartoçkasynda görkezilýär.',
  productsNote: 'Üýtgeşmeleri sahypa geçirmek üçin «Çap et» basyň. Ýüklenen suratlar serwerde saklanýar we awtomatik kiçeldilýär.',
  loginTitle: 'Admin paneli',
  loginSubtitle: 'Döwletli mazmun redaktory',
  username: 'Ulanyjy ady',
  password: 'Açar sözi',
  wrongCreds: 'Ulanyjy ady ýa-da açar sözi nädogry.',
  checking: 'Barlanýar…',
  signIn: 'Gir',
  backToSite: '← Sahypa dolan',
  confirmResetContent: 'ÄHLI tekstleri başlangyç görnüşe dikeltmeli? Bu yza gaýtarylmaýar.',
  confirmResetProducts: 'Başlangyç 5 önümi dikeltmeli?',
  confirmDeleteProduct: 'Bu önümi pozmaly? Bu yza gaýtarylmaýar.',
  confirmClearRequests: 'ÄHLI haýyşlary pozmaly?',
  imported: 'Import edildi. «Çap et» basyň.',
  importError: 'Faýl okalmady. Dogry eksport faýly bolandygyna göz ýetiriň.',
  imageTooBig: 'Surat örän uly. 20 MB-dan kiçi faýl ulanyň.',
  tabGallery: 'Galereýa',
  galleryTitle: 'Galereýa',
  gallerySubtitle: 'Galereýa sahypasyndaky suratlary goşuň/pozuň we sahypa suratlaryny saýlaň.',
  addImage: 'Surat goş',
  addFirstImage: 'Ilkinji suratyňyzy goşuň',
  noImages: 'Heniz surat ýok',
  galleryNote: 'Üýtgeşmeleri sahypa geçirmek üçin «Çap et» basyň. Suratlar serwerde saklanýar we awtomatik kiçeldilýär. Suraty pozman Galereýa sahypasyndan gizlemek üçin göz nyşanyny ulanyň.',
  confirmDeleteImage: 'Bu suraty pozmaly?',
  confirmResetGallery: 'Galereýany başlangyç suratlara dikeltmeli?',
  photoCategory: 'Kategoriýa',
  showInGallery: 'Galereýada görkez',
  hideFromGallery: 'Galereýadan gizle',
  hiddenLabel: 'Gizlenen',
  pageImages: 'Sahypa suratlary',
  mainBanner: 'Baş sahypa — banner',
  aboutImage: 'Biz barada — surat',
  fromGallery: 'Galereýadan',
  remove: 'Aýyr',
  noGalleryYet: 'Galereýada heniz surat ýok — aşakdan goşuň.',
  brandName: 'Brend ady (ýokarky we aşaky bölüm)',
  brandNameHint: 'Her sahypanyň ýokarsynda görkezilýär. Ähli dillerde birmeňzeş.',
  socialLinks: 'Sosial baglanyşyklar (Habarlaşmak we aşaky bölüm)',
  socialHint: 'Platforma saýlaň we baglanyşygy goýuň. Boş bolanlar sahypada görkezilmeýär.',
  addSocial: 'Sosial baglanyşyk goş',
  socialUrlPlaceholder: 'https://… ýa-da wa.me/…',
  adminLogin: 'Admin girişi',
  adminLoginHint: 'Bu panele girmek üçin ulanyjy adyny we açar sözüni üýtgediň.',
  newUsername: 'Ulanyjy ady',
  newPassword: 'Täze açar söz (azyndan 8 simwol)',
  updateLogin: 'Girişi täzele',
  loginUpdated: 'Giriş täzelendi. Indiki gezek täze ady we açar sözi ulanyň.',
  loginInvalid: 'Ulanyjy adyny we azyndan 8 simwolly açar söz giriziň.',
  loadingSite: 'Çap edilen sahypa ýüklenýär…',
  loadFailed: 'Çap edilen mazmuny serwerden ýükläp bolmady. Birikmäňizi barlap gaýtadan synanyşyň — ýüklenýänçä ýatda saklamak öçürildi.',
  retry: 'Gaýtadan synanyş',
  notPublishedYet: 'Serwere entek hiç zat çap edilmedi — myhmanlar häzir başlangyç tekstleri görýärler. Mazmuny barlaň we hemmelere çap etmek üçin «Çap et» basyň.',
  publishing: 'Çap edilýär…',
  uploadingImages: 'Suratlar ýüklenýär…',
  publishFailed: 'Çap edip bolmady — üýtgeşmeleriňiz entek sahypada DÄL. Gaýtadan synanyşyň.',
  conflictOverwrite: 'Paneli açanyňyzdan bäri sahypa başga enjamdan ýa-da goýmadan üýtgedildi. Öz wersiýaňyz bilen çalyşmalymy?',
  conflictInfo: 'Saklanmady. Iň soňky wersiýany almak üçin paneli täzeden açyň we üýtgeşmeleriňizi gaýtadan giriziň.',
  sessionExpired: 'Sessiýaňyzyň möhleti gutardy. Täzeden giriň.',
  tooManyAttempts: 'Örän köp şowsuz synanyşyk. 15 minut garaşyp, gaýtadan synanyşyň.',
  notConfigured: 'Admin girişi serwerde entek sazlanmadyk (Cloudflare-da ADMIN_PASSWORD gizlin açary ýok).',
  serverUnreachable: 'Serwere birigip bolmaýar. Birikmäňizi barlap, gaýtadan synanyşyň.',
  requestsLoadFailed: 'Haýyşlary serwerden ýükläp bolmady.',
  refresh: 'Täzele',
  accountFailed: 'Girişi täzeläp bolmady. Gaýtadan synanyşyň.',
  navDashboard: 'Umumy syn',
  navPages: 'Sahypalar we tekstler',
  navTheme: 'Tema we dizaýn',
  navSettings: 'Sazlamalar',
  interfaceLanguage: 'Panel dili',
  editingLanguage: 'Redaktirleme dili',
  publish: 'Çap et',
  statusPublished: 'Ähli üýtgeşmeler sahypada',
  statusUnsaved: 'Çap edilmedik üýtgeşmeler bar',
  statusNever: 'Entek çap edilmedi',
  discard: 'Üýtgeşmeleri ýatyr',
  confirmDiscard: 'Çap edilmedik ähli üýtgeşmeleri ýatyrmalymy?',
  lastPublished: 'Soňky çap',
  shortcutHint: 'Maslahat: Ctrl / ⌘ + S — çap et',
  welcome: 'Hoş geldiňiz',
  dashboardIntro: 'Sahypadaky ähli zat şu ýerden dolandyrylýar — tekstler, suratlar, önümler, tema we haýyşlar.',
  cardSiteStatus: 'Sahypanyň ýagdaýy',
  cardTheme: 'Häzirki tema',
  cardRequests: 'Täze haýyşlar',
  cardContent: 'Mazmun',
  productsCount: 'önüm',
  photosCount: 'galereýa suraty',
  languagesCount: 'dil',
  quickActions: 'Çalt hereketler',
  actEditHome: 'Baş sahypany üýtget',
  actChangeTheme: 'Temany üýtget',
  actViewRequests: 'Haýyşlary gör',
  latestRequests: 'Soňky haýyşlar',
  viewAll: 'Hemmesini gör',
  unreadCount: 'okalmadyk',
  pagesSubtitle: 'Sahypany saýlaň, tekstleri we suratlary üýtgediň — öňünden görkeziş derrew täzelenýär.',
  pageHeader: 'Sözbaşy we menýu',
  pageHome: 'Baş sahypa',
  pageAbout: 'Biz barada',
  pageProducts: 'Önümler sahypasy',
  pageGallery: 'Galereýa sahypasy',
  pageContact: 'Habarlaşmak',
  pageBooking: 'Ýazylmak',
  pageFooter: 'Aşaky bölüm',
  pageSeo: 'SEO we brauzer goýmasy',
  pageOther: 'Beýleki tekstler',
  compareLangs: 'Ähli 3 dili görkez',
  visibleSections: 'Bölümleri görkez / gizle',
  sec_headerBook: 'Sözbaşydaky «Ýazyl» düwmesi',
  sec_heroStats: 'Esasy suratyň aşagyndaky sanlar',
  sec_homeFeatures: 'Artykmaçlyk kartlary',
  sec_homeManufacturing: 'Önümçilik bölümi',
  sec_homeCta: 'Çagyryş banneri',
  sec_footerAdminLink: 'Aşakdaky «Admin» salgysy',
  logo: 'Logo (brauzer nyşany hem)',
  homeImage: 'Baş sahypa — önümçilik suraty',
  pageImagesHint: 'Galereýadan saýlaň ýa-da täze surat ýükläň.',
  bookingTimes: 'Elýeterli wagtlar',
  bookingTimesHint: 'Myhmanlar şu wagtlaryň birini saýlap bilýär.',
  addTime: 'Wagt goş',
  bookingDays: 'Öňünden görkezilýän günler',
  seoHint: 'Brauzer goýmasynda we Google netijelerinde görünýär.',
  noFieldsMatch: 'Gözlegiňize laýyk meýdan ýok.',
  textsSection: 'Tekstler',
  imagesSection: 'Suratlar',
  deviceDesktop: 'Kompýuter',
  deviceTablet: 'Planşet',
  deviceMobile: 'Telefon',
  previewDraftNote: 'Çap edilmedik üýtgeşmeleri görkezýär',
  openPreview: 'Öňünden gör',
  close: 'Ýap',
  themeSubtitle: 'Ähli sahypa üçin tema saýlaň. Ol derrew öňünden görkezişde görünýär we «Çap et» basylanda sahypa geçýär.',
  currentBadge: 'Saýlandy',
  defaultBadge: 'Asyl',
  darkBadge: 'Garaňky',
  customize: 'Takyk sazlama',
  customizeHint: 'Hökmany däl: saýlanan temany sazlaň. Boş goýsaňyz, temanyň öz bahalary ulanylýar.',
  primaryColor: 'Esasy reňk',
  accentColor: 'Öwüşgin reňki',
  headingFont: 'Sözbaşy şrifti',
  bodyFont: 'Tekst şrifti',
  corners: 'Burçlar',
  cornersTheme: 'Temadaky ýaly',
  cornersSharp: 'Ýiti',
  cornersSoft: 'Ýumşak',
  cornersRound: 'Tegelek',
  resetCustom: 'Sazlamany yzyna gaýtar',
  fontsNote: 'Ähli şriftler latyn, türkmen we kiril harplaryny goldaýar.',
  settingsSubtitle: 'Brend, sosial salgylar, admin girişi we ätiýaçlyk nusgalar.',
  brandSection: 'Brend',
  backupTitle: 'Ätiýaçlyk nusga',
  backupHint: 'Hemme zady (tekstler, önümler, galereýa, tema, sazlamalar) bir faýl edip ýükläň ýa-da yzyna ýükläň.',
  downloadBackup: 'Nusgany ýükle',
  restoreBackup: 'Faýldan ýükle',
  restored: 'Nusga ýüklendi. Öňünden görkezişi barlaň we «Çap et» basyň.',
  resetAllTitle: 'Hemmesini yzyna gaýtar',
  resetAllHint: 'Ähli tekstleri, önümleri, galereýany, temany we sazlamalary asyl sahypa gaýtaryň. Çap edilýänçä hiç zat üýtgemeýär.',
  confirmResetAll: 'Hemme zady asyl sahypa gaýtarmalymy? Çap edilýänçä hiç zat üýtgemeýär.',
  resetPage: 'Bu sahypany yzyna gaýtar',
  confirmResetPage: 'Bu sahypanyň tekstlerini (ähli dillerde) asyl ýagdaýa gaýtarmalymy?',
  menu: 'Menýu',
  remoteNewer: 'Sahypa başga enjamdan ýa-da goýmadan täzelendi. Ony üstünden ýazmazlyk üçin iň soňky wersiýany ýükläň.',
  loadLatest: 'Iň soňkusyny ýükle',
  newBadge: 'täze',
  missingTranslation: 'Terjime ýok — iňlisçesi görkeziler',
  invalidTime: 'SS:MM görnüşini ulanyň, mysal üçin 09:30',
  confirmRestore: 'Bu nusgany ýüklemelimi? Ol häzirki garalamany çalyşar (çap edilýänçä sahypa hiç zat geçmez).',
  notBackup: 'Bu faýl Döwletli ätiýaçlyk nusgasy däl.',
  page404: 'Tapylmady sahypasy (404)',
};

const DICTS: Record<Lang, Dict> = { en, ru, tkm };

export function adminT(lang: Lang) {
  const dict = DICTS[lang] || en;
  return (key: AdminKey): string => dict[key] ?? en[key];
}

// ---- Content section & field labels (translated) ---------------------------

function humanize(key: string): string {
  return key
    .replace(/([A-Z])/g, ' $1')
    .replace(/[_-]/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase())
    .trim();
}

// Top-level section card headers
const SECTIONS: Record<Lang, Record<string, string>> = {
  en: {
    brand: 'Brand name & tagline', nav: 'Menu / Navigation', hero: 'Home — main banner',
    home: 'Home — sections', features: 'Home — features', products: 'Products page',
    about: 'About page', contact: 'Contact page', booking: 'Booking page',
    gallery: 'Gallery page', footer: 'Footer', seo: 'Browser tab & Google', notFound: 'Not-found page (404)',
  },
  ru: {
    brand: 'Название и слоган', nav: 'Меню / Навигация', hero: 'Главная — баннер',
    home: 'Главная — разделы', features: 'Главная — преимущества', products: 'Страница продукции',
    about: 'Страница «О нас»', contact: 'Страница контактов', booking: 'Страница записи',
    gallery: 'Страница галереи', footer: 'Подвал сайта', seo: 'Вкладка браузера и Google', notFound: 'Страница «не найдено» (404)',
  },
  tkm: {
    brand: 'Brend ady we şygary', nav: 'Menýu / Nawigasiýa', hero: 'Baş sahypa — banner',
    home: 'Baş sahypa — bölümler', features: 'Baş sahypa — aýratynlyklar', products: 'Önümler sahypasy',
    about: 'Biz barada sahypasy', contact: 'Habarlaşmak sahypasy', booking: 'Ýazgy sahypasy',
    gallery: 'Galereýa sahypasy', footer: 'Aşaky bölüm', seo: 'Brauzer goýmasy we Google', notFound: 'Tapylmady sahypasy (404)',
  },
};

// Field & nested-group labels (keyed by the last path segment)
const FIELDS: Record<string, Record<Lang, string>> = {
  title: { en: 'Title', ru: 'Заголовок', tkm: 'Ady' },
  subtitle: { en: 'Subtitle', ru: 'Подзаголовок', tkm: 'Kömekçi ýazgy' },
  description: { en: 'Description', ru: 'Описание', tkm: 'Düşündiriş' },
  label: { en: 'Label', ru: 'Метка', tkm: 'Bellik' },
  name: { en: 'Name', ru: 'Имя', tkm: 'Ady' },
  tagline: { en: 'Tagline', ru: 'Слоган', tkm: 'Şygar' },
  highlight: { en: 'Highlighted word', ru: 'Выделенное слово', tkm: 'Bellenen söz' },
  cta: { en: 'Button (CTA)', ru: 'Кнопка', tkm: 'Düwme' },
  book: { en: 'Booking button', ru: 'Кнопка записи', tkm: 'Ýazgy düwmesi' },
  button: { en: 'Button', ru: 'Кнопка', tkm: 'Düwme' },
  // nav items
  home: { en: 'Home', ru: 'Главная', tkm: 'Baş sahypa' },
  about: { en: 'About', ru: 'О нас', tkm: 'Biz barada' },
  products: { en: 'Products', ru: 'Продукция', tkm: 'Önümler' },
  gallery: { en: 'Gallery', ru: 'Галерея', tkm: 'Galereýa' },
  contact: { en: 'Contact', ru: 'Контакты', tkm: 'Habarlaşmak' },
  // hero stats
  stat1num: { en: 'Stat 1 — number', ru: 'Показатель 1 — число', tkm: 'Görkeziji 1 — san' },
  stat1label: { en: 'Stat 1 — label', ru: 'Показатель 1 — подпись', tkm: 'Görkeziji 1 — ýazgy' },
  stat2num: { en: 'Stat 2 — number', ru: 'Показатель 2 — число', tkm: 'Görkeziji 2 — san' },
  stat2label: { en: 'Stat 2 — label', ru: 'Показатель 2 — подпись', tkm: 'Görkeziji 2 — ýazgy' },
  stat3num: { en: 'Stat 3 — number', ru: 'Показатель 3 — число', tkm: 'Görkeziji 3 — san' },
  stat3label: { en: 'Stat 3 — label', ru: 'Показатель 3 — подпись', tkm: 'Görkeziji 3 — ýazgy' },
  // home
  manufacturing: { en: 'Manufacturing', ru: 'Производство', tkm: 'Önümçilik' },
  stats: { en: 'Stats', ru: 'Показатели', tkm: 'Görkezijiler' },
  cycle: { en: 'Production cycle', ru: 'Производственный цикл', tkm: 'Önümçilik tapgyry' },
  quality: { en: 'Quality', ru: 'Качество', tkm: 'Hil' },
  badge: { en: 'Badge', ru: 'Бейдж', tkm: 'Bellik' },
  global: { en: 'Global', ru: 'Глобально', tkm: 'Global' },
  reliable: { en: 'Reliability', ru: 'Надёжность', tkm: 'Ynamdarlyk' },
  // products
  viewDetails: { en: 'View details', ru: '«Подробнее»', tkm: '«Jikme-jik»' },
  categories: { en: 'Categories', ru: 'Категории', tkm: 'Kategoriýalar' },
  aerial: { en: 'Aerial', ru: 'Воздушный', tkm: 'Howa' },
  underground: { en: 'Underground', ru: 'Подземный', tkm: 'Ýerasty' },
  ftth: { en: 'FTTH', ru: 'FTTH', tkm: 'FTTH' },
  directBurial: { en: 'Direct burial', ru: 'Прямая укладка', tkm: 'Göni gömme' },
  // about
  story: { en: 'Story', ru: 'История', tkm: 'Taryh' },
  history: { en: 'History', ru: 'История', tkm: 'Taryh' },
  expansion: { en: 'Expansion', ru: 'Расширение', tkm: 'Giňeltmek' },
  mission: { en: 'Mission', ru: 'Миссия', tkm: 'Wezipe' },
  // contact
  hero_title: { en: 'Page title', ru: 'Заголовок страницы', tkm: 'Sahypa ady' },
  labels: { en: 'Labels', ru: 'Метки', tkm: 'Bellikler' },
  location: { en: 'Location', ru: 'Местоположение', tkm: 'Ýerleşýän ýeri' },
  phone: { en: 'Phone', ru: 'Телефон', tkm: 'Telefon' },
  email: { en: 'Email', ru: 'Эл. почта', tkm: 'E-poçta' },
  form: { en: 'Form', ru: 'Форма', tkm: 'Forma' },
  message: { en: 'Message', ru: 'Сообщение', tkm: 'Habar' },
  send: { en: 'Send', ru: 'Отправить', tkm: 'Iber' },
  sending: { en: 'Sending…', ru: 'Отправка…', tkm: 'Iberilýär…' },
  success: { en: 'Success message', ru: 'Сообщение об успехе', tkm: 'Üstünlik habary' },
  sent: { en: 'After-send note', ru: 'Текст после отправки', tkm: 'Iberilenden soňky ýazgy' },
  info: { en: 'Contact info', ru: 'Контактные данные', tkm: 'Habarlaşmak maglumaty' },
  address: { en: 'Address', ru: 'Адрес', tkm: 'Salgy' },
  mobile: { en: 'Mobile', ru: 'Мобильный', tkm: 'Jübi telefony' },
  badges: { en: 'Badges', ru: 'Бейджи', tkm: 'Bellikler' },
  facility: { en: 'Facility', ru: 'Объект', tkm: 'Desga' },
  error: { en: 'Error message', ru: 'Сообщение об ошибке', tkm: 'Ýalňyşlyk habary' },
  featuresEyebrow: { en: 'Features — small tag', ru: 'Преимущества — метка', tkm: 'Artykmaçlyklar — bellik' },
  featuresTitle: { en: 'Features — heading', ru: 'Преимущества — заголовок', tkm: 'Artykmaçlyklar — sözbaşy' },
  cycleValue: { en: 'Stat 1 — number', ru: 'Цифра 1', tkm: 'San 1' },
  qualityValue: { en: 'Stat 2 — number', ru: 'Цифра 2', tkm: 'San 2' },
  eyebrow: { en: 'Small tag above the title', ru: 'Метка над заголовком', tkm: 'Sözbaşynyň üstündäki bellik' },
  adminLink: { en: '“Admin” link text', ru: 'Текст ссылки «Админ»', tkm: '«Admin» salgy teksti' },
  hint: { en: 'Note under the heading', ru: 'Пояснение под заголовком', tkm: 'Sözbaşynyň aşagyndaky bellik' },
  text: { en: 'Text', ru: 'Текст', tkm: 'Tekst' },
  sendMessage: { en: '“Send message” heading', ru: 'Заголовок «Сообщение»', tkm: '«Habar iber» sözbaşy' },
  // booking
  selectService: { en: 'Select service', ru: 'Выбор услуги', tkm: 'Hyzmat saýlamak' },
  selectDate: { en: 'Select date', ru: 'Выбор даты', tkm: 'Sene saýlamak' },
  selectTime: { en: 'Select time', ru: 'Выбор времени', tkm: 'Wagt saýlamak' },
  yourInfo: { en: 'Your info', ru: 'Ваши данные', tkm: 'Maglumatyňyz' },
  confirm: { en: 'Confirm', ru: 'Подтвердить', tkm: 'Tassyklamak' },
  services: { en: 'Services', ru: 'Услуги', tkm: 'Hyzmatlar' },
  technical: { en: 'Technical', ru: 'Технические', tkm: 'Tehniki' },
  sales: { en: 'Sales', ru: 'Продажи', tkm: 'Satuw' },
  tour: { en: 'Tour', ru: 'Экскурсия', tkm: 'Gezelenç' },
  next: { en: 'Next', ru: 'Далее', tkm: 'Indiki' },
  back: { en: 'Back', ru: 'Назад', tkm: 'Yza' },
  summary: { en: 'Summary', ru: 'Сводка', tkm: 'Jemi' },
  fullName: { en: 'Full name', ru: 'Полное имя', tkm: 'Doly ady' },
  emailAddress: { en: 'Email address', ru: 'Эл. почта', tkm: 'E-poçta salgysy' },
  edit: { en: 'Edit', ru: 'Изменить', tkm: 'Üýtgetmek' },
  steps: { en: 'Steps', ru: 'Шаги', tkm: 'Ädimler' },
  service: { en: 'Service', ru: 'Услуга', tkm: 'Hyzmat' },
  datetime: { en: 'Date & time', ru: 'Дата и время', tkm: 'Sene we wagt' },
  details: { en: 'Details', ru: 'Детали', tkm: 'Maglumatlar' },
  benefits: { en: 'Benefits', ru: 'Преимущества', tkm: 'Artykmaçlyklar' },
  expertTitle: { en: 'Benefit 1 — title', ru: 'Преимущество 1 — заголовок', tkm: 'Artykmaçlyk 1 — ady' },
  expertDesc: { en: 'Benefit 1 — text', ru: 'Преимущество 1 — текст', tkm: 'Artykmaçlyk 1 — tekst' },
  customTitle: { en: 'Benefit 2 — title', ru: 'Преимущество 2 — заголовок', tkm: 'Artykmaçlyk 2 — ady' },
  customDesc: { en: 'Benefit 2 — text', ru: 'Преимущество 2 — текст', tkm: 'Artykmaçlyk 2 — tekst' },
  // footer
  company: { en: 'Company', ru: 'Компания', tkm: 'Kompaniýa' },
  technology: { en: 'Technology', ru: 'Технологии', tkm: 'Tehnologiýa' },
  careers: { en: 'Careers', ru: 'Карьера', tkm: 'Karýera' },
  news: { en: 'News', ru: 'Новости', tkm: 'Habarlar' },
  rights: { en: 'Rights text', ru: 'Текст о правах', tkm: 'Hukuklar ýazgysy' },
  // gallery
  filters: { en: 'Filters', ru: 'Фильтры', tkm: 'Süzgüçler' },
  all: { en: 'All', ru: 'Все', tkm: 'Hemmesi' },
  factory: { en: 'Factory', ru: 'Завод', tkm: 'Fabrik' },
  events: { en: 'Events', ru: 'События', tkm: 'Çäreler' },
};

export function sectionLabel(key: string, lang: Lang): string {
  return SECTIONS[lang]?.[key] ?? SECTIONS.en[key] ?? humanize(key);
}

export function fieldLabel(key: string, lang: Lang): string {
  return FIELDS[key]?.[lang] ?? humanize(key);
}

// Short explanations for the built-in product categories (shown on hover in the
// Products manager). Custom categories typed by the admin have no hint.
const CATEGORY_HINTS: Record<string, Record<Lang, string>> = {
  aerial: {
    en: 'Overhead cables strung between poles or towers (ADSS, figure-8, self-supporting).',
    ru: 'Воздушные кабели, подвешиваемые между опорами (ADSS, «восьмёрка», самонесущие).',
    tkm: 'Sütünleriň arasyndan asylýan howa kabelleri (ADSS, sekiz görnüşli, öz-özüni göteriji).',
  },
  underground: {
    en: 'Cables pulled through underground ducts or conduits.',
    ru: 'Кабели, протягиваемые в подземных каналах или трубах.',
    tkm: 'Ýerasty turbalardan ýa-da kanaldan çekilýän kabeller.',
  },
  ftth: {
    en: 'Fiber-to-the-Home — drop and indoor cables to subscriber premises.',
    ru: 'Оптика до дома (FTTH) — абонентские (drop) и внутренние кабели.',
    tkm: 'Öýe çenli optika (FTTH) — abonent (drop) we içerki kabeller.',
  },
  directBurial: {
    en: 'Armored cables laid directly in the ground without ducts.',
    ru: 'Бронированные кабели, укладываемые прямо в грунт без каналов.',
    tkm: 'Kanalsyz, göni ýere gömülýän sowutly kabeller.',
  },
};

export function categoryHint(key: string, lang: Lang): string | null {
  return CATEGORY_HINTS[key]?.[lang] ?? null;
}
